apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-deployment
  labels:
    app: udacity-capstone-deployment
    type: restapi
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-capstone
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: udacity-capstone-tmpl
        app: udacity-capstone
    spec:
      containers:
        - image: izzyandrade/udacity-capstone:latest
          imagePullPolicy: Always
          name: udacity-capstone
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-svc
  labels:
    app: udacity-capstone-svc
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone-deployment
  ports:
    - port: 8000
      targetPort: 5000
      protocol: TCP
