apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-app
  labels:
    app: udacity-capstone-app
    type: restapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone-app
  # strategy:
  #   rollingUpdate:
  #     maxUnavailable: 1
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        name: udacity-capstone-tmpl
        app: udacity-capstone-app
    spec:
      containers:
        - image: izzyandrade/udacity-capstone:latest
          imagePullPolicy: Always
          name: udacity-capstone-app
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-svc
  labels:
    app: udacity-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
