apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  selector:
    matchLabels:
      app: udacity-capstone
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
        - name: udacity-capstone
          image: izzyandrade/udacity-capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-deployment
  labels:
    app: udacity-capstone-deployment
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone-deployment
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
