apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
